# Generated by Django 3.1 on 2020-08-04 21:06
import re
import json
from django.db import migrations

MODEL_FIELDS = [
    'title',
    'authors',
    'publishedDate',
    'categories',
    'averageRating',
    'ratingsCount',
    'thumbnail'
]

JSON_FILE = 'volumes.json'


def camel_to_snake(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()


def load_data(apps, schema_editor):
    Book = apps.get_model('apps.books', 'Book')

    with open(JSON_FILE) as datafile:
        objects = json.load(datafile)
        books = objects.get('items')

    def get_book(book):
        volume_info = book['volumeInfo']
        book_data = {}
        for k in volume_info.keys():
            if k in MODEL_FIELDS:
                book_data[camel_to_snake(k)] = volume_info.get(k)
        book_data['thumbnail'] = volume_info['imageLinks']['thumbnail']

        return book_data

    for book_data in books:
        book = Book(**get_book(book_data))
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
    ]
